### ISSUE TITLE
Onion seed

### ISSUE THREAD

**Issue by KlausT** [chainworksindustries/sweepstakecoin#1]
My client only get 1 address from the onion seed.
Is this the way it's supposed to work?
Or is there a problem somewhere?

```
05/19/17 17:04:54 ThreadDNSAddressSeed started
05/19/17 17:04:54 Loading addresses from DNS seeds (could take a while)
05/19/17 17:04:54 0 addresses found from DNS seeds
05/19/17 17:04:54 ThreadDNSAddressSeed exited
05/19/17 17:04:54 ThreadSocketHandler started
05/19/17 17:04:54 ThreadOpenAddedConnections started
05/19/17 17:04:54 ThreadOpenAddedConnections exited
05/19/17 17:04:54 ThreadMessageHandler started
05/19/17 17:04:54 ThreadStakeMiner started
05/19/17 17:04:54 ThreadOnionSeed started
05/19/17 17:04:54 Loading addresses from .onion seeds
05/19/17 17:04:54 ThreadOpenConnections started
05/19/17 17:04:54 ThreadMapPort started
05/19/17 17:04:54 Added pgpc4wtqm2ar4tbm.onion:17570 from pgpc4wtqm2ar4tbm.onion: 0 tried, 1 new
05/19/17 17:04:54 1 addresses found from .onion seeds
05/19/17 17:04:54 ThreadOnionSeed exited
05/19/17 17:04:54 Flushed 1 addresses to peers.dat  100ms
```

**Comment by sweepstakecoin** [comment]
This is the def seed. In BCT thread someone should be able to post more seeds. Looks like the seed node is down, i restarted it. Possibly will need to add more seeds in the code in future.

**Comment by chrysophylax69** [comment]
once we get organized in the coming days - we will get them sorted ...

need to create a number of them - and hardcode them ...

strasboug - we need your help to create the first seed ... ill message you on bct ...

#crysx

**Comment by chrysophylax69** [comment]
removal of tor completed - so this issue will be closed ...

you are more than welcome to help out klaust ...

#crysx
