### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by combat007** [chainworksindustries/sweepstakecoin#4]
wallet compiled on ubuntu 16.04
but terminates after starting throwing the following error

sni-qt void StatusNotifierItemFactory::connectToSnw() invalid interface to  SNW_SERVICE

core dumped

**Comment by chrysophylax69** [comment]
Hi combat007,

Did you compile from HEAD/Master?

If so, it will not work. The current code is broken for the time being, as we wanted to remove TOR altogether.

What you will need to do is clone from Master then checkout from the previous commit.

ie ...

git clone https://github.com/chainworksindustries/sweepstakecoin.git && git checkout https://github.com/chainworksindustries/sweepstakecoin/commit/2cc44248478fb5878e61df553a1ce4b0dceb11b5
cd sweepstakecoin

... and then proceed to make either daemon or qt or both.

Hope this helps.

#crysx

**Comment by combat007** [comment]
it says not a git repository

**Comment by barrystyle** [comment]
git clone https://github.com/chainworksindustries/sweepstakecoin
cd sweepstakecoin
git checkout 2cc4424847

then build as standard from there..

**Comment by combat007** [comment]
git checkout did not work for me
so I downloaded it from
https://github.com/chainworksindustries/sweepstakecoin/tree/2cc44248478fb5878e61df553a1ce4b0dceb11b5

and compiled it normally
It worked like a charm

Thanks for all your kind support & info!!
